server:
  port: 8082

spring:
  application:
    name: bankaccounts-microservice
  config:
    import: configserver:http://localhost:8888
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

health:
  config:
    enabled=false:

logging:
  config:
  file: logback-spring.xml


