name: AzureSpringCloud
on: push
env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  AZURE_SUBSCRIPTION: ${{ secrets.AZURE_CREDENTIALS.subscriptionId }}

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: deploy to production with artifact
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: maven compile, clean
        run: |
          mvn clean package -DskipTests
      - name: Login to Azure Spring Cloud
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Install Azure Spring Cloud extension
        run: az extension add --name spring-cloud
      - name: Deploy to Azure Spring Cloud
        run: az spring-cloud app deploy --name accountmicroservice --service azurespringboot2022  --resource-group AzureSpringBoot --artifact-path target/bankaccount-0.0.1.jar
